name: CI

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/*
      - src/**
      - '*.php'
      - composer.*
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  ci:
    name: ğŸ‘· CI S for PHP-${{ matrix.php-version }} (${{
      matrix.dependency-version }}) on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: true
      matrix:
        operating-system: [ubuntu-latest]
        php-version: [8.4]
        dependency-version: [prefer-lowest, prefer-stable]
    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v4

      - name: ğŸ§± Install submodules
        run: git submodule update --init --recursive

      - name: ğŸ“‚ Cache dependencies
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-php-${{ matrix.php }}-composer-

      - name: ğŸ›  Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: curl, dom, gd, intl, mbstring, openssl, tokenizer, zip
          ini-values: error_reporting=E_ALL
          tools: composer:v2, php-cs-fixer, phpunit, vimeo/psalm
          coverage: pcov

      - name: ğŸ“¦ Install Dependencies
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: -q --ignore-platform-reqs --no-ansi --no-cache --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader --classmap-authoritative

      - name: âœ… Run Code Lint
        run: composer check

      - name: âš—ï¸ Run Static Analysis
        run: |
          composer analyse
          composer inspect

      - name: ğŸ§ Run Code Review
        run: composer review

      - name: ğŸ§ª Run Feature Tests
        run: composer test
